### PR TITLE
Add rpm

### PR DESCRIPTION
**Pull request by rickr**
Create RPM for agent

### CODE REVIEW

**Comment by fermayo** [comment]
Thanks for this rikr!

In which distros have you tested this? @tifayuki can help with testing

**Comment by rickr** [comment]
Hello @fermayo. This is currently installed and running on a DO CentOS 7 box:

[root@tutum-agent run]# uname -a
Linux tutum-agent 3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@tutum-agent run]# cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)

I can spin up a CentOS 6 box to test as well if that helps.

**Comment by tifayuki** [comment]
@rickr @fermayo 
I installed the rpm in cetos7 in Do, it works fine.

We can remove the following dependencies,  I think:
sqlite-devel is needed by tutum-agent-0.14.0-1.x86_64
nmap-ncat is needed by tutum-agent-0.14.0-1.x86_64

PS: I replaced `nc` command with golang's net.Dial() function in staging, and `nmap-ncat` is no longer needed.

**Comment by rickr** [comment]
@tifayuki @fermayo Thanks for the feedback Feng. I've removed those deps from make-rpm.

**Comment by tifayuki** [comment]
@rickr can you open the pull request against staging and squash the  commits?

Thank you so much :)

**Pull request closed without merging**
